(* 
Copyright 2004, Richard Cole

This file is part of Griff.

Griff is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or (at your
option) any later version.

Griff is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License
along with Griff; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*)

open Pmm_lang
open Pmm_util
open Pmm_lang_ast
open Printf

let collect_asl_from_n 
  (field: string) (node: pmm_node) (z: string Rb_set.tree) =
  let collect_asl field_node z =
    let pat = (Str.regexp " and ") in
    let asl = Str.split pat (get_text field_node) in
      List.fold_right Rb_set.insert asl z
  in
    fold_right_children field collect_asl node z

let collect_asl_field_from_nl field nodes =
  List.fold_right (collect_asl_from_n field) nodes Rb_set.empty


let print_authors print_author nodes =
  let authors = collect_asl_field_from_nl "authors" nodes in
    Rb_set.iter print_author authors

let print_paper_ref ch node =
  let id = get_first_field_text "id" node in
  let title = get_first_field_text "title" node in
    fprintf ch 
"    <a href=\"bookmarks.html#%s\">%s</a><br>"
      id title

let print_author ch nl k =
  fprintf ch 
"    <entry id=\"%s\">
     <div class=\"titleText\"><h2>%s</h2></div>
     <div class=\"contentText\">
" k k;
  fprintf ch "<p class=\"attribute\"><b>Papers:</b><br>";
  List.iter 
    (print_paper_ref ch) 
    (select_nodes (with_field_contains_asv "authors" k) nl);
  fprintf ch "</p>";
  fprintf ch
"    </div></entry>
"
;;

let ch = stdout in
  fprintf ch "<html>
  <!-- 
          DO NOT EDIT THIS FILE IT IS AUTOGENERATED FROM bookmarks.txt
  -->
  <title>Bookmarks</title>
  <link 
     rel=\"stylesheet\" media=\"screen\" type=\"text/css\" 
     href=\"styleone.css\"
  />
<body>
  <div class=\"titleBar\"><center><h1>Papers Indexed by Author</h1></center></div>
";
  let nl = pmm_of_channel_name Sys.argv.(1) in
    print_authors (print_author ch nl) nl;
 fprintf ch "</body></html>"

;;
